### ISSUE TITLE
Simple fix

### ISSUE THREAD

**Issue by richardmark** [juliusberner/oberwolfach_workshop#2]
interact(lambda k: plot_1d(R(Conc([P('triangle') for _ in range(k)])), 
                            interval=[-0.5,1.5], num=1e+5), k=(1,5));
Will throw an error now can not convert float to int

Simple fix

interact(lambda k: plot_1d(R(Conc([P('triangle') for _ in range(k)])), 
                            interval=[-0.5,1.5], num=100000), k=(1,5));

**Comment by richardmark** [comment]
The fix above was for NN_Approximation.ipynb which is a very well done module. 

Hopefully we will have  modules like yours explaining the mathematical foundations for Graph Neural Networks  (GNN) in a similar way.  I have always been somewhat skeptical on just how far NN and DNN would get us in ML. Luckily most but not all of our data is on manifolds that can be captured by just the approaches of DNN. Hopefully GNN will take us beyond DNN. My gut tells me GNN are a better way to move forward not just in ML but also in what may pass for what many would consider "consciousness" - that is acting in a way so close to what would pass for being "conscious" that who knows if the app is or isn't "conscious" since nothing I can do can prove if anyone else possesses "consciousness" .

**Comment by juliusberner** [comment]
fixed, thank you very much!

I also believe that GNNs are a promising new direction and hope to analyze their mathematical properties soon.
